### ISSUE TITLE
启动 oj_web_server出错

### ISSUE THREAD

**Issue by mcmdhr** [QingdaoU/OnlineJudge#10]
执行
```
docker run --name oj_web_server -e oj_env=server -e smtp_password={SMTP_PASSWORD} -v /home/OnlineJudge:/code  -v /home/log:/code/log -v /home/upload:/code/upload -v /home/test_case:/code/test_case -d -p 127.0.0.1:8080:8080 --link=redis --link=mysql oj_web_server
```
出错
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                     PORTS               NAMES
07d105757a2a        oj_web_server       "/bin/sh -c 'bash /co"   5 seconds ago       Exited (1) 2 seconds ago                       oj_web_server
```
log:
```
Compiling /code/utils/xss_filter.py ...
/usr/local/lib/python2.7/site-packages/supervisor/options.py:296: UserWarning: Supervisord is running as root and it is searching for its configuration file in default locations (including its current working directory); you probably want to specify a "-c" argument specifying an absolute path to a configuration file for improved security.
  'Supervisord is running as root and it is searching '
Traceback (most recent call last):
  File "/usr/local/bin/supervisord", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/supervisor/supervisord.py", line 367, in main
    go(options)
  File "/usr/local/lib/python2.7/site-packages/supervisor/supervisord.py", line 377, in go
    d.main()
  File "/usr/local/lib/python2.7/site-packages/supervisor/supervisord.py", line 77, in main
    info_messages)
  File "/usr/local/lib/python2.7/site-packages/supervisor/options.py", line 1387, in make_logger
    stdout = self.nodaemon,
  File "/usr/local/lib/python2.7/site-packages/supervisor/loggers.py", line 346, in getLogger
    handlers.append(RotatingFileHandler(filename,'a',maxbytes,backups))
  File "/usr/local/lib/python2.7/site-packages/supervisor/loggers.py", line 172, in __init__
    FileHandler.__init__(self, filename, mode)
  File "/usr/local/lib/python2.7/site-packages/supervisor/loggers.py", line 98, in __init__
    self.stream = open(filename, mode)
IOError: [Errno 13] Permission denied: '/code/log/supervisord.log'
```

**Comment by virusdefender** [comment]
文件权限问题。

看下你主机上log目录的权限和用户组

**Comment by mcmdhr** [comment]
啊，是这个问题。。。但是出现了新问题
```
[root@iZ28hn7wya3Z ~]# chown -R nobody:nogroup /root/workspace/test_case /root/workspace/log /root/workspace/upload
chown: 无效的组: "nobody:nogroup"
```
我在centos7上执行均出现这个问题，您在部署的时候遇到过这个问题吗？

**Comment by mcmdhr** [comment]
再补充一下，我部署的时候没有完全按照wiki来，直接在root下创建的目录，这样会有影响吗？

**Comment by virusdefender** [comment]
路劲在哪都一样，主要是对应替换配置文件中路径对应替换和正确设置文件权限。

看样子 CentOS 上 `nobody` 不是 `nogroup` 组的，你尝试运行`id nobody`看看这个用户是哪个组的。

我一直都在 Ubuntu 上测试的，CentOS 并不太熟悉。

**Comment by mcmdhr** [comment]
已解决，可能是supervisor 或者操作系统的问题。
在CentOS下，log文件夹，要用`chmod 777` 才行，以及centos下没有nogroup组，可以改成nobody组。目前docker跑起来了，后面还待配置

**Comment by virusdefender** [comment]
好的~ `chmod 777`其实也行，gunicorn 等是 nobody 用户跑的，所以需要修改下权限。
