### ISSUE TITLE
oj_web_server内py脚本执行出错

### ISSUE THREAD

**Issue by mcmdhr** [QingdaoU/OnlineJudge#11]
```
root@ce42e8c45003:/code# python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 302, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/code/oj/settings.py", line 23, in <module>
    from .server_settings import *
  File "/code/oj/server_settings.py", line 13, in <module>
    'USER': os.environ["MYSQL_ENV_MYSQL_USER"],
  File "/usr/local/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'MYSQL_ENV_MYSQL_USER'
```

没错。。。还是我23333333

**Comment by virusdefender** [comment]
你 link mysql 的 docker 了么

这个 `MYSQL_ENV_MYSQL_USER`是 `docker --link mysql:mysql`之后会自动添加的环境变量

**Comment by virusdefender** [comment]
看来我得抓紧把 docker compose 的版本更新上来，手动操作 docker 确实很容易出错。

**Comment by mcmdhr** [comment]
link过了，有密码－ －没有MYSQL_ENV_MYSQL_USER
然后我自己添加了一个，这个错误没了，然后报了其他错误
```
root@1a40081d5414:/code# python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 302, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/site-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/code/oj/settings.py", line 25, in <module>
    from .custom_settings import *
ImportError: No module named custom_settings
```
然后看了下oj底下
```
root@1a40081d5414:/code/oj# ls
__init__.py   celery.py   custom_settings.example.py   db_router.py   local_settings.py   server_settings.py   settings.py   urls.py   wsgi.py
__init__.pyc  celery.pyc  custom_settings.example.pyc  db_router.pyc  local_settings.pyc  server_settings.pyc  settings.pyc  urls.pyc  wsgi.pyc
```
不知道这是什么原因了

**Comment by virusdefender** [comment]
看文档 

> 然后复制 oj/custom_settings.example.py 为 oj/custom_settings.py，里面有一些个性化配置，比如网站名称域名等，可以先保持默认，以后再修改。
