### ISSUE TITLE
提交问题答案时，系统一直提示　ｓｙｓｔｅｍ　ｅｒｒｏｒ

### ISSUE THREAD

**Issue by AngleMAXIN** [QingdaoU/OnlineJudge#192]
这是我的judger.log的全部内容，提交问题答案时，系统一直提示　ｓｙｓｔｅｍ　ｅｒｒｏｒ
FATAL [2018-11-21 08:06:36] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 08:06:46] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 08:06:56] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 08:07:20] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 08:07:56] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 08:08:33] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 08:09:01] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 08:14:47] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 08:15:36] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 08:16:21] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 08:20:37] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 08:20:57] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 08:45:03] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 09:05:33] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 09:09:10] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 09:15:20] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 09:35:25] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 09:56:14] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 09:58:53] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 10:28:06] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 10:28:07] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 10:28:07] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 10:28:12] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 10:32:57] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 10:35:53] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 10:36:01] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 10:45:11] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 10:46:40] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 10:47:30] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 10:47:38] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 11:06:37] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 11:26:07] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 11:50:20] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-21 12:22:40] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-22 03:29:33] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-22 12:17:14] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED
FATAL [2018-11-22 13:17:54] [/tmp/Judger/src/child.c:87]Error: System errno: No such file or directory; Internal errno: DUP2_FAILED

这是judger_server.log的部分内容，因为太多了，大部分都是重复错误
Traceback (most recent call last):
  File "/code/service.py", line 41, in <module>
    service.heartbeat()
  File "/code/service.py", line 35, in heartbeat
    self._request(data)
  File "/code/service.py", line 29, in _request
    raise JudgeServiceError("Invalid heartbeat response")
exception.JudgeServiceError
2018-11-21 08:05:55,126 ERROR 
Traceback (most recent call last):
  File "/code/server.py", line 142, in server
    ret = {"err": None, "data": getattr(JudgeServer, path)(**data)}
  File "/code/server.py", line 78, in judge
    output_dir=submission_dir)
  File "/code/compiler.py", line 42, in compile
    raise CompileError(error)
exception.CompileError
2018-11-22 13:17:29,378 ERROR HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe953174320>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fe953174320>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe953174320>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/service.py", line 19, in _request
    "Content-Type": "application/json"}, timeout=5).text
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe953174320>: Failed to establish a new connection: [Errno 111] Connection refused',))
2018-11-22 13:17:29,382 ERROR 
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fe953174320>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe953174320>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/service.py", line 19, in _request
    "Content-Type": "application/json"}, timeout=5).text
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='oj-backend', port=8000): Max retries exceeded with url: /api/judge_server_heartbeat/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fe953174320>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/service.py", line 41, in <module>
    service.heartbeat()
  File "/code/service.py", line 35, in heartbeat
    self._request(data)
  File "/code/service.py", line 22, in _request
    raise JudgeServiceError("Heartbeat request failed")
exception.JudgeServiceError

**Comment by virusdefender** [comment]
感觉你的测试用例文件丢了输入，重新上传一下看看
