### ISSUE TITLE
django.db.utils.OperationalError: could not connect to server: Connection refused

### ISSUE THREAD

**Issue by Origami404** [QingdaoU/OnlineJudge#210]
我尝试修改前端,为了debug需要, 想单独运行一个后端

如果可以希望作者在文档中加入后端依赖.
我通过报错得到了以下依赖列表

```
django celery raven envelopes djangorestframework psycopg2-binary coverage qrcode otpauth xlsxwriter django-redis python-dateutil jsonfield
```

不清楚本项目使用的django版本, 但在本人安装的django@2.1.4中, 可能需要对以下文件做出以下修改:(原因参考了[Django2.0 ForeignKey 变化](https://www.jianshu.com/p/2610fec14d26))

`OnlineJudge/announcement/models.py`第12行

`OnlineJudge/contest/models.py`第23行, 第59行, 第60行和第93行

`OnlineJudge/problem/models.py`第31行, 第50行

`OnlineJudge/submission/models.py`第25行, 第26行

中的`models.ForeignKey(xxx)`后加上参数
```python
on_delete=models.CASCADE
```

在完成以上修改后运行
```bash
python manage.py runserver
```
后完整报错如下
```
Django VERSION (2, 1, 4, 'final', 0)
Django VERSION (2, 1, 4, 'final', 0)
Performing system checks...

System check identified no issues (0 silenced).
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f319821ebf8>
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/usr/lib/python3.7/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 5433?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
    self.check_migrations()
  File "/usr/lib/python3.7/site-packages/django/core/management/base.py", line 442, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/usr/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/lib/python3.7/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 61, in applied_migrations
    if self.has_table():
  File "/usr/lib/python3.7/site-packages/django/db/migrations/recorder.py", line 44, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/usr/lib/python3.7/site-packages/django/db/backends/base/base.py", line 255, in cursor
    return self._cursor()
  File "/usr/lib/python3.7/site-packages/django/db/backends/base/base.py", line 232, in _cursor
    self.ensure_connection()
  File "/usr/lib/python3.7/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/usr/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/lib/python3.7/site-packages/django/db/backends/base/base.py", line 216, in ensure_connection
    self.connect()
  File "/usr/lib/python3.7/site-packages/django/db/backends/base/base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 178, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/lib/python3.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not connect to server: Connection refused
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 5433?
```

Google后结果大多表示是`psycopg2`的数据链接的问题, 但不知从何修改,也不确定是不是.请问如何解决?

**Comment by virusdefender** [comment]
你数据库怎么运行的，错误就是连不上数据库
