### ISSUE TITLE
fps导入失败！

### ISSUE THREAD

**Issue by YuFengZe** [QingdaoU/OnlineJudge#338]
在提交issue之前请

  - 认真阅读文档 http://docs.onlinejudge.me/#/
  - 搜索和查看历史issues
  - 安全类问题请不要在 GitHub 上公布，请发送邮件到 `admin@qduoj.com`，根据漏洞危害程度发送红包感谢。
 
然后提交issue请写清楚下列事项
 
  - 进行什么操作的时候遇到了什么问题，最好能有复现步骤
  - 错误提示是什么，如果看不到错误提示，请去data文件夹查看相应log文件。大段的错误提示请包在代码块标记里面。
  - 你尝试修复问题的操作
  - 页面问题请写清浏览器版本，尽量有截图

环境：ubuntu18.04

使用上传fps功能上传xml文件时，点击upload上传后，提示server error。
xml文件地址：https://github.com/zhblue/freeproblemset/blob/master/fps-examples/fps-loj-small-pics.zip

gunicorn.log：
`[2020-11-15 15:45:54] - [ERROR] - [root:156]  - Invalid xml, error 'test_input' tag order
Traceback (most recent call last):
  File "/app/utils/api/api.py", line 149, in dispatch
    return super(APIView, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/app/problem/views/admin.py", line 683, in post
    problems = FPSParser(tf.name).parse()
  File "/app/fps/parser.py", line 32, in parse
    ret.append(self._parse_one_problem(node))
  File "/app/fps/parser.py", line 97, in _parse_one_problem
    raise ValueError("Invalid xml, error 'test_input' tag order")
ValueError: Invalid xml, error 'test_input' tag order
[2020-11-15 15:45:59] - [ERROR] - [sentry.errors:684]  - Sentry responded with an API error: RateLimited(None)
b'Sentry responded with an API error: RateLimited(None)'
[2020-11-15 15:46:00] - [ERROR] - [sentry.errors.uncaught:712]  - ["Invalid xml, error 'test_input' tag order", '  File "utils/api/api.py", line 149, in dispatch', '  File "django/views/generic/base.py", line 88, in dispatch', '  File "problem/views/admin.py", line 683, in post', '  File "fps/parser.py", line 32, in parse', '  File "fps/parser.py", line 97, in _parse_one_problem']
`
另外，使用旧版本迁移时，当有题目为special judge时（没有样例），会直接停止程序！

**Comment by Wendy417** [comment]
您好，我也遇到了同样的问题，请问您解决了吗？

**Comment by ttzytt** [comment]
遇到同样问题了

**Comment by booox** [comment]
同样问题

**Comment by FishZe** [comment]
可以看一下这个[Issue](https://github.com/QingdaoU/OnlineJudge/issues/328)
