### ISSUE TITLE
golang无法编译运行

### ISSUE THREAD

**Issue by SamPeng87** [QingdaoU/OnlineJudge#339]
Compile Error
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f592bf8df47 m=5 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7f592bf8df47
stack: frame={sp:0x7f58e7ffe7e0, fp:0x0} stack=[0x7f58dffff288,0x7f58e7ffee88)
00007f58e7ffe6e0:  0000000000000000  00007f592c342c58 
00007f58e7ffe6f0:  00007f58e7ffea90  00007f592c57675a 
00007f58e7ffe700:  000000000000000b  0000000000000000 
00007f58e7ffe710:  ffffffffffffff78  0000000000d800c0 
00007f58e7ffe720:  00007f58e7ffebf0  00000000018c7690 
00007f58e7ffe730:  0000000000000000  0000000000aeeeb8 
00007f58e7ffe740:  0000000000000000  00007f592c56ef13 
00007f58e7ffe750:  0000000000000005  0000000000000000 
00007f58e7ffe760:  2525252525252525  2525252525252525 
00007f58e7ffe770:  0000000000000000  0000000000000000 
00007f58e7ffe780:  0000000000000000  0000000000000000 
00007f58e7ffe790:  4d6c6f72746e6f43  6f6e3d7265747361 
00007f58e7ffe7a0:  7273752f3d485441  732f6c61636f6c2f 
00007f58e7ffe7b0:  7273752f3a6e6962  622f6c61636f6c2f 
00007f58e7ffe7c0:  2f7273752f3a6e69  73752f3a6e696273 
00007f58e7ffe7d0:  732f3a6e69622f72  6e69622f3a6e6962 
00007f58e7ffe7e0: <0000000000000000  656c696166206574 
00007f58e7ffe7f0:  0000000000000000  0000000000000000 
00007f58e7ffe800:  000000c000128660  000000000000000d 
00007f58e7ffe810:  000000c00012a4a0  0000000000000015 
00007f58e7ffe820:  000000c000124270  0000000000000027 
00007f58e7ffe830:  0405060700010203  0c0d0e0f08090a0b 
00007f58e7ffe840:  000000c00059f680  000000c00059f800 
00007f58e7ffe850:  000000c00059f980  000000c00059fb00 
00007f58e7ffe860:  fffffffe7fffffff  ffffffffffffffff 
00007f58e7ffe870:  ffffffffffffffff  ffffffffffffffff 
00007f58e7ffe880:  ffffffffffffffff  ffffffffffffffff 
00007f58e7ffe890:  ffffffffffffffff  ffffffffffffffff 
00007f58e7ffe8a0:  ffffffffffffffff  ffffffffffffffff 
00007f58e7ffe8b0:  ffffffffffffffff  ffffffffffffffff 
00007f58e7ffe8c0:  ffffffffffffffff  ffffffffffffffff 
00007f58e7ffe8d0:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0x7f592bf8df47
stack: frame={sp:0x7f58e7ffe7e0, fp:0x0} stack=[0x7f58dffff288,0x7f58e7ffee88)
00007f58e7ffe6e0:  0000000000000000  00007f592c342c58 
00007f58e7ffe6f0:  00007f58e7ffea90  00007f592c57675a 
00007f58e7ffe700:  000000000000000b  0000000000000000 
00007f58e7ffe710:  ffffffffffffff78  0000000000d800c0 
00007f58e7ffe720:  00007f58e7ffebf0  00000000018c7690 
00007f58e7ffe730:  0000000000000000  0000000000aeeeb8 
00007f58e7ffe740:  0000000000000000  00007f592c56ef13 
00007f58e7ffe750:  0000000000000005  0000000000000000 
00007f58e7ffe760:  2525252525252525  2525252525252525 
00007f58e7ffe770:  0000000000000000  0000000000000000 
00007f58e7ffe780:  0000000000000000  0000000000000000 
00007f58e7ffe790:  4d6c6f72746e6f43  6f6e3d7265747361 
00007f58e7ffe7a0:  7273752f3d485441  732f6c61636f6c2f 
00007f58e7ffe7b0:  7273752f3a6e6962  622f6c61636f6c2f 
00007f58e7ffe7c0:  2f7273752f3a6e69  73752f3a6e696273 
00007f58e7ffe7d0:  732f3a6e69622f72  6e69622f3a6e6962 
00007f58e7ffe7e0: <0000000000000000  656c696166206574 
00007f58e7ffe7f0:  0000000000000000  0000000000000000 
00007f58e7ffe800:  000000c000128660  000000000000000d 
00007f58e7ffe810:  000000c00012a4a0  0000000000000015 
00007f58e7ffe820:  000000c000124270  0000000000000027 
00007f58e7ffe830:  0405060700010203  0c0d0e0f08090a0b 
00007f58e7ffe840:  000000c00059f680  000000c00059f800 
00007f58e7ffe850:  000000c00059f980  000000c00059fb00 
00007f58e7ffe860:  fffffffe7fffffff  ffffffffffffffff 
00007f58e7ffe870:  ffffffffffffffff  ffffffffffffffff 
00007f58e7ffe880:  ffffffffffffffff  ffffffffffffffff 
00007f58e7ffe890:  ffffffffffffffff  ffffffffffffffff 
00007f58e7ffe8a0:  ffffffffffffffff  ffffffffffffffff 
00007f58e7ffe8b0:  ffffffffffffffff  ffffffffffffffff 
00007f58e7ffe8c0:  ffffffffffffffff  ffffffffffffffff 
00007f58e7ffe8d0:  ffffffffffffffff  ffffffffffffffff 

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xc0005951a8)
	/usr/lib/go-1.15/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc0005951a0)
	/usr/lib/go-1.15/src/sync/waitgroup.go:130 +0x65
cmd/go/internal/work.(*Builder).Do(0xc00013b540, 0xc00038ab40)
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:188 +0x3b1
cmd/go/internal/work.runBuild(0xdc6a80, 0xc000130040, 0x1, 0x1)
	/usr/lib/go-1.15/src/cmd/go/internal/work/build.go:423 +0x6aa
main.main()
	/usr/lib/go-1.15/src/cmd/go/main.go:190 +0x58d

goroutine 6 [select]:
cmd/go/internal/work.(*Builder).Do.func3(0xc0005951a0, 0xc00013b540, 0xc000120540)
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:169 +0xff
created by cmd/go/internal/work.(*Builder).Do
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:166 +0x38d

goroutine 7 [select]:
cmd/go/internal/work.(*Builder).Do.func3(0xc0005951a0, 0xc00013b540, 0xc000120540)
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:169 +0xff
created by cmd/go/internal/work.(*Builder).Do
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:166 +0x38d

goroutine 8 [select]:
cmd/go/internal/work.(*Builder).Do.func3(0xc0005951a0, 0xc00013b540, 0xc000120540)
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:169 +0xff
created by cmd/go/internal/work.(*Builder).Do
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:166 +0x38d

goroutine 9 [select]:
cmd/go/internal/work.(*Builder).Do.func3(0xc0005951a0, 0xc00013b540, 0xc000120540)
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:169 +0xff
created by cmd/go/internal/work.(*Builder).Do
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:166 +0x38d

goroutine 10 [select]:
cmd/go/internal/work.(*Builder).Do.func3(0xc0005951a0, 0xc00013b540, 0xc000120540)
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:169 +0xff
created by cmd/go/internal/work.(*Builder).Do
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:166 +0x38d

goroutine 11 [select]:
cmd/go/internal/work.(*Builder).Do.func3(0xc0005951a0, 0xc00013b540, 0xc000120540)
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:169 +0xff
created by cmd/go/internal/work.(*Builder).Do
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:166 +0x38d

goroutine 12 [select]:
cmd/go/internal/work.(*Builder).Do.func3(0xc0005951a0, 0xc00013b540, 0xc000120540)
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:169 +0xff
created by cmd/go/internal/work.(*Builder).Do
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:166 +0x38d

goroutine 13 [select]:
cmd/go/internal/work.(*Builder).Do.func3(0xc0005951a0, 0xc00013b540, 0xc000120540)
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:169 +0xff
created by cmd/go/internal/work.(*Builder).Do
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:166 +0x38d

goroutine 14 [select]:
cmd/go/internal/work.(*Builder).Do.func3(0xc0005951a0, 0xc00013b540, 0xc000120540)
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:169 +0xff
created by cmd/go/internal/work.(*Builder).Do
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:166 +0x38d

goroutine 15 [select]:
cmd/go/internal/work.(*Builder).Do.func3(0xc0005951a0, 0xc00013b540, 0xc000120540)
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:169 +0xff
created by cmd/go/internal/work.(*Builder).Do
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:166 +0x38d

goroutine 16 [select]:
cmd/go/internal/work.(*Builder).Do.func3(0xc0005951a0, 0xc00013b540, 0xc000120540)
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:169 +0xff
created by cmd/go/internal/work.(*Builder).Do
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:166 +0x38d

goroutine 50 [select]:
cmd/go/internal/work.(*Builder).Do.func3(0xc0005951a0, 0xc00013b540, 0xc000120540)
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:169 +0xff
created by cmd/go/internal/work.(*Builder).Do
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:166 +0x38d

goroutine 51 [select]:
cmd/go/internal/work.(*Builder).Do.func3(0xc0005951a0, 0xc00013b540, 0xc000120540)
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:169 +0xff
created by cmd/go/internal/work.(*Builder).Do
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:166 +0x38d

goroutine 52 [select]:
cmd/go/internal/work.(*Builder).Do.func3(0xc0005951a0, 0xc00013b540, 0xc000120540)
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:169 +0xff
created by cmd/go/internal/work.(*Builder).Do
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:166 +0x38d

goroutine 53 [select]:
cmd/go/internal/work.(*Builder).Do.func3(0xc0005951a0, 0xc00013b540, 0xc000120540)
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:169 +0xff
created by cmd/go/internal/work.(*Builder).Do
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:166 +0x38d

goroutine 54 [chan receive]:
os/exec.(*Cmd).Wait(0xc000168dc0, 0x0, 0x0)
	/usr/lib/go-1.15/src/os/exec/exec.go:515 +0x131
os/exec.(*Cmd).Run(0xc000168dc0, 0xc0005888d0, 0x11)
	/usr/lib/go-1.15/src/os/exec/exec.go:341 +0x5c
cmd/go/internal/work.(*Builder).toolID(0xc00013b540, 0xa35eeb, 0x7, 0xb, 0xc0004bf410)
	/usr/lib/go-1.15/src/cmd/go/internal/work/buildid.go:192 +0x45c
cmd/go/internal/work.(*Builder).buildActionID(0xc00013b540, 0xc00038b2c0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:251 +0xd14
cmd/go/internal/work.(*Builder).build(0xc00013b540, 0xc00038b2c0, 0x0, 0x0)
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:406 +0x504a
cmd/go/internal/work.(*Builder).Do.func2(0xc00038b2c0)
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:119 +0x362
cmd/go/internal/work.(*Builder).Do.func3(0xc0005951a0, 0xc00013b540, 0xc000120540)
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:179 +0x76
created by cmd/go/internal/work.(*Builder).Do
	/usr/lib/go-1.15/src/cmd/go/internal/work/exec.go:166 +0x38d

goroutine 56 [runnable]:
os/exec.(*Cmd).Start.func1(0xc000168dc0, 0xc000120620)
	/usr/lib/go-1.15/src/os/exec/exec.go:440
created by os/exec.(*Cmd).Start
	/usr/lib/go-1.15/src/os/exec/exec.go:440 +0x629

rax    0x0
rbx    0x7f592c33b840
rcx    0x7f592bf8df47
rdx    0x0
rdi    0x2
rsi    0x7f58e7ffe7e0
rbp    0xb0975c
rsp    0x7f58e7ffe7e0
r8     0x0
r9     0x7f58e7ffe7e0
r10    0x8
r11    0x246
r12    0x18c7690
r13    0x0
r14    0xaeeeb8
r15    0x0
rip    0x7f592bf8df47
rflags 0x246
cs     0x33
fs     0x0
gs     0x0

**Comment by farmerboy95** [comment]
I'm having the same issue, with Docker on MacOS Big Sur, Go 1.16, but when reducing the max_stack, it disappears. Any idea why?

**Comment by SuQiucheng** [comment]
I have the same issue,did you slove this probrlem

**Comment by virusdefender** [comment]
I fixed in https://github.com/QingdaoU/OnlineJudge/commit/99b145e37cf29cc963bc369119f19d381efd0de2

You can try to update the latest version, and then reset the compiler options https://opensource.qduoj.com/#/onlinejudge/guide/update_compile_options
