### ISSUE TITLE
AttributeError: 'Style' object has no attribute 'SUCCESS'

### ISSUE THREAD

**Issue by imcaffrey** [QingdaoU/OnlineJudge#34]
After running `python manage.py initadmin`, I get this:
```
oj@oj-Junyi-A410:/home/OnlineJudge$ sudo python manage.py initadmin
Super admin user 'root' already exists, would you like to reset it's password?
Input yes to confirm: 
yes
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/OnlineJudge/utils/management/commands/initadmin.py", line 19, in handle
    self.stdout.write(self.style.SUCCESS("Successfully created super admin user password.\n"
AttributeError: 'Style' object has no attribute 'SUCCESS'
```

**Comment by virusdefender** [comment]
```
import django
print django.VERSION
```
看下你django的版本

**Comment by imcaffrey** [comment]
1, 8, 4, final, 0

**Comment by imcaffrey** [comment]
都是现装的

**Comment by virusdefender** [comment]
1.9以上才行，见`dockerfiles/oj_web_server/requirements.txt`

**Comment by imcaffrey** [comment]
我就是按照requirements.txt装的啊……

**Comment by virusdefender** [comment]
requirements.txt应该是下载最新的啊
