### ISSUE TITLE
自己构建容器后judge_server状态一直unhealthy

### ISSUE THREAD

**Issue by zhangpj15** [QingdaoU/OnlineJudge#394]
因为提供的docker不支持arm架构，所以自己想自己构建一下，使用的构建命令为：
` docker build -t registry.cn-hangzhou.aliyuncs.com/onlinejudge/judge_server:latest .`
构建之后使用系统提供的compose文件开启服务：
`docker-compose up -d`
然后docker中的状态为：
![image](https://user-images.githubusercontent.com/32196265/145136158-36ebe02a-9356-41d7-bdc0-d37bed5abb27.png)
我也查看了judge_server的日志，结果如下：

Django VERSION (2, 1, 7, 'final', 0)
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 325, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 57, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.7/site-packages/django/conf/__init__.py", line 107, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/oj/settings.py", line 23, in <module>
    with open(os.path.join(DATA_DIR, "config", "secret.key"), "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/config/secret.key'
Failed to migrate, going to retry...
addgroup: /etc/group: Read-only file system
adduser: unknown group spj
chown: unknown user/group server:spj
find: /data/test_case: No such file or directory
find: /data/test_case: No such file or directory
Error: The directory named as part of the path /data/log/supervisord.log does not exist

想问一下该怎么解决

**Comment by Beichi-CHs** [comment]
你的构建应该就已经失败了...权限组好像都不存在，密钥也没有成功生成，建议重新选择一版python-alpine支持arm的底包看看
