### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by mozart25** [QingdaoU/OnlineJudge#409]
exception.CompileError
2022-04-11 04:41:28,920 ERROR
Traceback (most recent call last):
  File "/code/server.py", line 192, in server
    ret = {"err": None, "data": getattr(JudgeServer, path)(**data)}
  File "/code/server.py", line 99, in judge
    output_dir=submission_dir)
  File "/code/compiler.py", line 46, in compile
    raise CompileError("Compiler runtime error, info: %s" % json.dumps(result))
exception.CompileError

with C language and just simple add with two numbers. Why is that?

**Comment by zhangxu9622** [comment]
hello，I also encountered similar problems, did you solve it?

**Comment by mozart25** [comment]
i forgot what i answered. but i think i did aws ec2 re created with ubuntu
version not centos

2022년 6월 14일 (화) 오후 2:23, zhangxu9622 ***@***.***>님이 작성:

**Comment by zhangxu9622** [comment]
Is everything normal after aws ec2 recreated with ubuntu?I use Amazon Linux 2 AMI now

**Comment by mozart25** [comment]
yeah i definitely remembered that,

1st setting: aws ec2 with cent os

cent os was the problem.

but i changed into ubuntu os, then voila! did it i will send site later

2022년 6월 14일 (화) 오후 2:42, zhangxu9622 ***@***.***>님이 작성:

**Comment by zhangxu9622** [comment]
thank you！
> yeah i definitely remembered that, 1st setting: aws ec2 with cent os cent os was the problem. but i changed into ubuntu os, then voila! did it i will send site later

**Comment by mozart25** [comment]
https://www.youtube.com/watch?v=fqMYI04QHBM&ab_channel=%EC%A3%BC%EB%8B%88%EC%98%A8TV%EC%95%84%EB%AC%B4%EA%B1%B0%EB%82%98%EC%97%B0%EA%B5%AC%EC%86%8C

watch this!

2022년 6월 14일 (화) 오후 3:00, zhangxu9622 ***@***.***>님이 작성:
