### ISSUE TITLE
ImportError: No module named local

### ISSUE THREAD

**Issue by suchandd** [QingdaoU/OnlineJudge#9]
ubuntu@ubuntu-HP-15-Notebook-PC:~/Desktop/OnlineJudge-master$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 302, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named local

**Comment by virusdefender** [comment]
我试了下没有这个问题啊，你的 Django 版本是最新的么？

印象中就只有一个设置是 `oj/local_settings.py` 会在`oj/settings.py`中导入进来。

**Comment by JerryLeooo** [comment]
@virusdefender requirements.txt 中最好可以明确版本信息，以防止因为版本不一致带来的问题

**Comment by virusdefender** [comment]
@JerryLeooo 一直都是在用最新的，觉得还好了~
